<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
  <Actions category="Scripts">
    <text>Three slots</text>

    <Action name="activate_slot_1">
      <icon></icon>
      <text>Activate Eraser (Slot 1)</text>
      <whatsThis></whatsThis>
      <toolTip></toolTip>
      <iconText></iconText>
      <activationFlags>10000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>ctrl+alt+1</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="activate_slot_2">
      <icon></icon>
      <text>Activate Brush (Slot 2)</text>
      <whatsThis></whatsThis>
      <toolTip></toolTip>
      <iconText></iconText>
      <activationFlags>10000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>ctrl+alt+2</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="activate_slot_3">
      <icon></icon>
      <text>Activate Brush (Slot 3)</text>
      <whatsThis></whatsThis>
      <toolTip></toolTip>
      <iconText></iconText>
      <activationFlags>10000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>ctrl+alt+3</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="activate_slot_4">
      <icon></icon>
      <text>Activate Brush (Slot 4)</text>
      <whatsThis></whatsThis>
      <toolTip></toolTip>
      <iconText></iconText>
      <activationFlags>10000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>ctrl+alt+4</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>

  </Actions>
</ActionCollection>
